spring:
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${AUTH_DB_USERNAME}
        password: ${AUTH_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration
        user: ${AUTH_DB_USERNAME}
        password: ${AUTH_DB_PASSWORD}
        baseline-version: ${FLYWAY_BASELINE_VERSION}
    kafka:
        producer:
            bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.type.mapping: userCreated:com.patientapp.authservice.modules.notification.UserCreatedRequest,temporaryPassword:com.patientapp.authservice.modules.notification.TemporaryPasswordRequest
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope:
                            - profile
                            - email
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                    facebook:
                        client-id: ${FACEBOOK_CLIENT_ID}
                        client-secret: ${FACEBOOK_CLIENT_SECRET}
                        scope:
                            - public_profile
                            - email
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: sub
                    facebook:
                        authorization-uri: https://www.facebook.com/v10.0/dialog/oauth
                        token-uri: https://graph.facebook.com/v10.0/oauth/access_token
                        user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture
                        user-name-attribute: id

server:
    port: ${AUTH_SERVER_PORT}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH}
application:
    superadmin:
        email: ${SUPERADMIN_EMAIL}
        password: ${SUPERADMIN_PASSWORD}
    front-end:
        url: ${FRONT_END_URL}
        domain: ${FRONT_END_DOMAIN}
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
            expiration: ${JWT_EXPIRATION}
            refresh-token:
                expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
    config:
        doctor-url: ${DOCTOR_SERVICE_URL}
        patient-url: ${PATIENT_SERVICE_URL}