spring:
    datasource:
        url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${DOCTOR_DB_USERNAME}
        password: ${DOCTOR_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: false
    flyway:
        enabled: true
        baseline-on-migrate: true
        validate-on-migrate: true
        locations: classpath:db/migration
        user: ${DOCTOR_DB_USERNAME}
        password: ${DOCTOR_DB_PASSWORD}
        baseline-version: ${FLYWAY_BASELINE_VERSION}
server:
    port: ${DOCTOR_SERVER_PORT}
    servlet:
        context-path: ${SERVER_CONTEXT_PATH}

application:
    security:
        jwt:
            secret-key: ${JWT_SECRET_KEY}
    config:
        auth-url: ${AUTH_SERVICE_URL}
        appointment-url: ${APPOINTMENT_SERVICE_URL}